apiVersion: ctlptl.dev/v1alpha1
kind: Registry
name: ctlptl-registry
port: 5005
---
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
name: kind-kind
product: kind
kubernetesVersion: v1.32.2
registry: ctlptl-registry
