apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ .chart.ingressClass }}
  {{- if .Values.ingressClass.isDefaultClass }}
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
  {{- end }}
spec:
  controller: {{ default "maeshinshin.github.io/integrated-ingress-controller" .Values.ingressClass.controllerValue | quote }}
