# This rule is not used by the project cloudflare-nginx-ingress-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to networking.my.domain resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cloudflare-nginx-ingress-controller
    app.kubernetes.io/managed-by: kustomize
  name: ingress-viewer-role
rules:
- apiGroups:
  - networking.my.domain
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.my.domain
  resources:
  - ingresses/status
  verbs:
  - get
