apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/name: cloudflare-nginx-ingress-controller
    app.kubernetes.io/managed-by: kustomize
  name: ingress-sample
spec:
  # TODO(user): Add fields here
